#!/bin/sh -e

# Stopping oxd-server
if [ -x /etc/init.d/oxd-server-3.1.5 ]; then
service oxd-server-3.1.5 stop > /dev/null 2>&1
fi
chkconfig --del oxd-server-3.1.5 > /dev/null 2>&1

# Stopping oxd-https-extension
if [ -x /etc/init.d/oxd-https-extension ]; then
service oxd-https-extension stop > /dev/null 2>&1
fi
chkconfig --del oxd-https-extension > /dev/null 2>&1

exit 0
