#!/bin/sh -e

# Stopping oxd-server
if [ -x /etc/init.d/oxd-server-3.1.5 ]; then
/etc/init.d/oxd-server-3.1.5 stop > /dev/null 2>&1
fi

# Stopping oxd-https-extension
if [ -x /etc/init.d/oxd-https-extension ]; then
/etc/init.d/oxd-https-extension stop > /dev/null 2>&1
fi

exit 0
